=== canonical/ubuntu-security-notices/schema/USN-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/canonical/ubuntu-security-notices/main/schema/USN-schema.json",
  "title": "Ubuntu Security Notice",
  "description": "A schema for describing a a security update in Ubuntu.",
  "type": "object",
  "properties": {
    "id": {
      "description": "The Security Notice id, e.g USN-0001-1",
      "type": "string"
    },
    "action": {
      "description": "Instructions on how to upgrade",
      "type": "string"
    },
    "cves": {
      "description": "A list of CVEs related to this Notice",
      "type": "array",
      "items": {
        "description": "CVE ID in the form of CVE-YYYY-NNNN",
        "type": "string"
      }
    },
    "description": {
      "description": "The description of the issue as written by the Security Team",
      "type": "string"
    },
    "is_hidden": {
      "description": "Temporary field used for testing purposes",
      "type": "string"
    },
    "isummary": {
      "description": "Short description of the vulnerability",
      "type": "string"
    },
    "releases": {
      "description": "An entry for each release name",
      "type": "object"
    },
    "summary": {
      "description": "Source package name and type of update, e.g. python-django vulnerability",
      "type": "string"
    },
    "timestamp": {
      "description": "Date in epoch format",
      "type": "number"
    },
    "title": {
      "description": "Similar to summary, but using the Official project name instead of source package name",
      "type": "string"
    }
  },
  "required": [
    "description",
    "id",
    "releases",
    "summary",
    "timestamp",
    "title"
  ],
  "additionalProperties": false
}

=== canonical/ubuntu-security-notices/usn/USN-1814-1.json
{
  "description": "\nMathias Krause discovered an information leak in the Linux kernel's UDF\nfile system implementation. A local user could exploit this flaw to examine\nsome of the kernel's heap memory. (CVE-2012-6548)\n\nMathias Krause discovered an information leak in the Linux kernel's ISO\n9660 CDROM file system driver. A local user could exploit this flaw to\nexamine some of the kernel's heap memory. (CVE-2012-6549)\n\nAn integer overflow was discovered in the Direct Rendering Manager (DRM)\nsubsystem for the i915 video driver in the Linux kernel. A local user could\nexploit this flaw to cause a denial of service (crash) or potentially\nescalate privileges. (CVE-2013-0913)\n\nA format-string bug was discovered in the Linux kernel's ext3 filesystem\ndriver. A local user could exploit this flaw to possibly escalate\nprivileges on the system. (CVE-2013-1848)\n\nA buffer overflow was discovered in the Linux Kernel's USB subsystem for\ndevices reporting the cdc-wdm class. A specially crafted USB device when\nplugged-in could cause a denial of service (system crash) or possibly\nexecute arbitrary code. (CVE-2013-1860)\n\nA flaw was discovered in the SCTP (stream control transfer protocol)\nnetwork protocol's handling of duplicate cookies in the Linux kernel. A\nremote attacker could exploit this flaw to cause a denial of service\n(system crash) on another remote user querying the SCTP connection.\n(CVE-2013-2206)\n\nAn information leak in the Linux kernel's dcb netlink interface was\ndiscovered. A local user could obtain sensitive information by examining\nkernel stack memory. (CVE-2013-2634)\n\nA kernel stack information leak was discovered in the RTNETLINK component\nof the Linux kernel. A local user could read sensitive information from the\nkernel stack. (CVE-2013-2635)\n",
  "releases": {
    "quantal": {
      "sources": {
        "linux-ti-omap4": {
          "version": "3.5.0-223.34",
          "description": "Linux kernel for OMAP4"
        }
      },
      "binaries": {
        "linux-image-3.5.0-223-omap4": {
          "version": "3.5.0-223.34"
        }
      },
      "archs": {
        "source": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/l/linux-ti-omap4/linux-ti-omap4_3.5.0-223.34.dsc": {
              "size": 2211,
              "md5": "9c5fcda4908ff2c3396c70f7491dfabd"
            },
            "http://security.ubuntu.com/ubuntu/pool/main/l/linux-ti-omap4/linux-ti-omap4_3.5.0-223.34.tar.gz": {
              "size": 109097914,
              "md5": "4464f6932f09dcbfc78700fe5c18d000"
            }
          }
        },
        "armhf": {
          "urls": {
            "http://ports.ubuntu.com/pool/main/l/linux-ti-omap4/usb-modules-3.5.0-223-omap4-di_3.5.0-223.34_armhf.udeb": {
              "size": 83296,
              "md5": "818b36a5ade7891e080cbf0d018f0780"
            },
            "http://ports.ubuntu.com/pool/main/l/linux-ti-omap4/crypto-modules-3.5.0-223-omap4-di_3.5.0-223.34_armhf.udeb": {
              "size": 246542,
              "md5": "1dca7ce917345ef9e8bb486261d35123"
            },
            "http://ports.ubuntu.com/pool/main/l/linux-ti-omap4/storage-core-modules-3.5.0-223-omap4-di_3.5.0-223.34_armhf.udeb": {
              "size": 34464,
              "md5": "3790603bcc25720f75363f599fa75b7d"
            },
            "http://ports.ubuntu.com/pool/main/l/linux-ti-omap4/vlan-modules-3.5.0-223-omap4-di_3.5.0-223.34_armhf.udeb": {
              "size": 19234,
              "md5": "3ab399166b67f76fb0028db7d8df86df"
            },
            "http://ports.ubuntu.com/pool/main/l/linux-ti-omap4/nic-usb-modules-3.5.0-223-omap4-di_3.5.0-223.34_armhf.udeb": {
              "size": 161456,
              "md5": "d864f457aedbb9bb799df85117cc635e"
            },
            "http://ports.ubuntu.com/pool/main/l/linux-ti-omap4/ppp-modules-3.5.0-223-omap4-di_3.5.0-223.34_armhf.udeb": {
              "size": 21814,
              "md5": "3e4fbb514b9c4e2c3cc78b98dc3f4d80"
            },
            "http://ports.ubuntu.com/pool/main/l/linux-ti-omap4/parport-modules-3.5.0-223-omap4-di_3.5.0-223.34_armhf.udeb": {
              "size": 15088,
              "md5": "52741ff2c57cb3846406d92f67b9c5b8"
            },
            "http://ports.ubuntu.com/pool/main/l/linux-ti-omap4/scsi-modules-3.5.0-223-omap4-di_3.5.0-223.34_armhf.udeb": {
              "size": 161380,
              "md5": "c23a6ec37eafca838d6f9d2bd89f3646"
            },
            "http://ports.ubuntu.com/pool/main/l/linux-ti-omap4/fs-secondary-modules-3.5.0-223-omap4-di_3.5.0-223.34_armhf.udeb": {
              "size": 361372,
              "md5": "1d7ab198b7d0dbd7d9e234f616abf73d"
            },
            "http://ports.ubuntu.com/pool/main/l/linux-ti-omap4/block-modules-3.5.0-223-omap4-di_3.5.0-223.34_armhf.udeb": {
              "size": 21404,
              "md5": "527293616fa6d57d51bdf8d76db8569f"
            },
            "http://ports.ubuntu.com/pool/main/l/linux-ti-omap4/squashfs-modules-3.5.0-223-omap4-di_3.5.0-223.34_armhf.udeb": {
              "size": 15510,
              "md5": "5f3fc2b53048bae599757bbbd4c55eed"
            },
            "http://ports.ubuntu.com/pool/main/l/linux-ti-omap4/kernel-image-3.5.0-223-omap4-di_3.5.0-223.34_armhf.udeb": {
              "size": 4612932,
              "md5": "38d8aba8bc5299cb0cb180dc433a2196"
            },
            "http://ports.ubuntu.com/pool/main/l/linux-ti-omap4/linux-image-3.5.0-223-omap4_3.5.0-223.34_armhf.deb": {
              "size": 22064604,
              "md5": "74533f719cdbdbd2bc2045acbeeea647"
            },
            "http://ports.ubuntu.com/pool/main/l/linux-ti-omap4/irda-modules-3.5.0-223-omap4-di_3.5.0-223.34_armhf.udeb": {
              "size": 147554,
              "md5": "2236b9e1c6035ee6ad0d71c4cc149266"
            },
            "http://ports.ubuntu.com/pool/main/l/linux-ti-omap4/nic-modules-3.5.0-223-omap4-di_3.5.0-223.34_armhf.udeb": {
              "size": 202164,
              "md5": "4a55ccbbcdcdee4afe83d5d13d7ed2a0"
            },
            "http://ports.ubuntu.com/pool/main/l/linux-ti-omap4/fat-modules-3.5.0-223-omap4-di_3.5.0-223.34_armhf.udeb": {
              "size": 2166,
              "md5": "2d0b7b27170e6cdc656313b64d86cf02"
            },
            "http://ports.ubuntu.com/pool/main/l/linux-ti-omap4/plip-modules-3.5.0-223-omap4-di_3.5.0-223.34_armhf.udeb": {
              "size": 7482,
              "md5": "43e8b103903aa355c9512535588cb088"
            },
            "http://ports.ubuntu.com/pool/main/l/linux-ti-omap4/linux-headers-3.5.0-223_3.5.0-223.34_armhf.deb": {
              "size": 12198688,
              "md5": "fe5070614bc799b5c3d8c165723374ca"
            },
            "http://ports.ubuntu.com/pool/main/l/linux-ti-omap4/linux-ti-omap4-tools-3.5.0-223_3.5.0-223.34_armhf.deb": {
              "size": 331606,
              "md5": "2e8c22d40aeb060d5c267428f4f6fd2a"
            },
            "http://ports.ubuntu.com/pool/main/l/linux-ti-omap4/linux-headers-3.5.0-223-omap4_3.5.0-223.34_armhf.deb": {
              "size": 905598,
              "md5": "6fb37dc5e50ed5afaf70db2456864433"
            },
            "http://ports.ubuntu.com/pool/main/l/linux-ti-omap4/sata-modules-3.5.0-223-omap4-di_3.5.0-223.34_armhf.udeb": {
              "size": 15522,
              "md5": "84fe03412f456f7edfd4b559ae8ebf24"
            },
            "http://ports.ubuntu.com/pool/main/l/linux-ti-omap4/input-modules-3.5.0-223-omap4-di_3.5.0-223.34_armhf.udeb": {
              "size": 72494,
              "md5": "2bd65a31460e2e52d3ed785db5fd7c93"
            },
            "http://ports.ubuntu.com/pool/main/l/linux-ti-omap4/fs-core-modules-3.5.0-223-omap4-di_3.5.0-223.34_armhf.udeb": {
              "size": 446262,
              "md5": "9c9c66528948525088528c5ffd8d7f50"
            },
            "http://ports.ubuntu.com/pool/main/l/linux-ti-omap4/md-modules-3.5.0-223-omap4-di_3.5.0-223.34_armhf.udeb": {
              "size": 149654,
              "md5": "c84a798a0ea7f471c6912b2b0f4d59f6"
            },
            "http://ports.ubuntu.com/pool/main/l/linux-ti-omap4/mouse-modules-3.5.0-223-omap4-di_3.5.0-223.34_armhf.udeb": {
              "size": 36106,
              "md5": "94ad148907600e902a9d0d8197b120a6"
            },
            "http://ports.ubuntu.com/pool/main/l/linux-ti-omap4/nic-shared-modules-3.5.0-223-omap4-di_3.5.0-223.34_armhf.udeb": {
              "size": 260956,
              "md5": "b944c30d4d7c27c96b6e313b542ae463"
            }
          }
        }
      }
    }
  },
  "title": "Linux kernel (OMAP4) vulnerabilities",
  "timestamp": 1367494279.477327,
  "summary": "linux-ti-omap4 vulnerabilities",
  "action": "After a standard system update you need to reboot your computer to make\nall the necessary changes.\n\nATTENTION: Due to an unavoidable ABI change the kernel updates have\nbeen given a new version number, which requires you to recompile and\nreinstall all third party kernel modules you might have installed. If\nyou use linux-restricted-modules, you have to update that package as\nwell to get modules which work with the new kernel version. Unless you\nmanually uninstalled the standard kernel metapackages (e.g. linux-generic,\nlinux-server, linux-powerpc), a standard system upgrade will automatically\nperform this as well.\n",
  "cves": [
    "CVE-2012-6548",
    "CVE-2012-6549",
    "CVE-2013-0913",
    "CVE-2013-1848",
    "CVE-2013-1860",
    "CVE-2013-2206",
    "CVE-2013-2634",
    "CVE-2013-2635"
  ],
  "id": "USN-1814-1",
  "isummary": "Several security issues were fixed in the kernel.\n"
}

=== canonical/ubuntu-security-notices/usn/USN-2153-1.json
{
  "description": "Kees Cook discovered that initramfs-tools incorrectly mounted /run without\nthe noexec option, contrary to expected behaviour.\n",
  "releases": {
    "precise": {
      "sources": {
        "initramfs-tools": {
          "version": "0.99ubuntu13.5",
          "description": "tools for generating an initramfs"
        }
      },
      "binaries": {
        "initramfs-tools": {
          "version": "0.99ubuntu13.5"
        }
      },
      "archs": {
        "all": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/i/initramfs-tools/initramfs-tools_0.99ubuntu13.5_all.deb": {
              "md5": "32fee251acf21c0906f8a12b46dcad55",
              "size": 49016
            }
          }
        },
        "amd64": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/i/initramfs-tools/initramfs-tools-bin_0.99ubuntu13.5_amd64.deb": {
              "md5": "b243a727386b4728721d18849b2ade91",
              "size": 9782
            }
          }
        },
        "powerpc": {
          "urls": {
            "http://ports.ubuntu.com/pool/main/i/initramfs-tools/initramfs-tools-bin_0.99ubuntu13.5_powerpc.deb": {
              "md5": "1b378f32bdce37d10b539b8db6924d04",
              "size": 9714
            }
          }
        },
        "source": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/i/initramfs-tools/initramfs-tools_0.99ubuntu13.5.tar.gz": {
              "md5": "0ac188b92de52ae164b21b7b7ffeaf81",
              "size": 112167
            },
            "http://security.ubuntu.com/ubuntu/pool/main/i/initramfs-tools/initramfs-tools_0.99ubuntu13.5.dsc": {
              "md5": "7f72339e92b7b7c0a5cefff576de4de9",
              "size": 1847
            }
          }
        },
        "i386": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/i/initramfs-tools/initramfs-tools-bin_0.99ubuntu13.5_i386.deb": {
              "md5": "4dd390305215bc97465a9f5f2e3af9ea",
              "size": 9648
            }
          }
        },
        "armel": {
          "urls": {
            "http://ports.ubuntu.com/pool/main/i/initramfs-tools/initramfs-tools-bin_0.99ubuntu13.5_armel.deb": {
              "md5": "50ef3354177db0701a82b8cb2c76d5f4",
              "size": 9204
            }
          }
        },
        "armhf": {
          "urls": {
            "http://ports.ubuntu.com/pool/main/i/initramfs-tools/initramfs-tools-bin_0.99ubuntu13.5_armhf.deb": {
              "md5": "546263e19ff7e63d95490c0ec4e03df6",
              "size": 9206
            }
          }
        }
      }
    },
    "quantal": {
      "sources": {
        "initramfs-tools": {
          "version": "0.103ubuntu0.2.2",
          "description": "tools for generating an initramfs"
        }
      },
      "binaries": {
        "initramfs-tools": {
          "version": "0.103ubuntu0.2.2"
        }
      },
      "archs": {
        "all": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/i/initramfs-tools/initramfs-tools_0.103ubuntu0.2.2_all.deb": {
              "md5": "567f3839370e1a93636bf8a7231c4e5b",
              "size": 48572
            }
          }
        },
        "amd64": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/i/initramfs-tools/initramfs-tools-bin_0.103ubuntu0.2.2_amd64.deb": {
              "md5": "4e54ae576da6a0383385c6c9ef582623",
              "size": 9692
            }
          }
        },
        "powerpc": {
          "urls": {
            "http://ports.ubuntu.com/pool/main/i/initramfs-tools/initramfs-tools-bin_0.103ubuntu0.2.2_powerpc.deb": {
              "md5": "40eecd573af2e16d3517f1bb8c53532e",
              "size": 9638
            }
          }
        },
        "source": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/i/initramfs-tools/initramfs-tools_0.103ubuntu0.2.2.tar.gz": {
              "md5": "e77a0ab5d95d03a7bbca22a4d4abb5cc",
              "size": 112259
            },
            "http://security.ubuntu.com/ubuntu/pool/main/i/initramfs-tools/initramfs-tools_0.103ubuntu0.2.2.dsc": {
              "md5": "70f035458aacc8f141ebad109a6f7590",
              "size": 1855
            }
          }
        },
        "i386": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/i/initramfs-tools/initramfs-tools-bin_0.103ubuntu0.2.2_i386.deb": {
              "md5": "85df12c76160bcd335e273f2baa9e6dc",
              "size": 9638
            }
          }
        },
        "armel": {
          "urls": {
            "http://ports.ubuntu.com/pool/main/i/initramfs-tools/initramfs-tools-bin_0.103ubuntu0.2.2_armel.deb": {
              "md5": "8f414a55782d3d3b2a555314fd99b2de",
              "size": 9382
            }
          }
        },
        "armhf": {
          "urls": {
            "http://ports.ubuntu.com/pool/main/i/initramfs-tools/initramfs-tools-bin_0.103ubuntu0.2.2_armhf.deb": {
              "md5": "ade3c527563700ad795fbb77d63ad757",
              "size": 9186
            }
          }
        }
      }
    }
  },
  "title": "initramfs-tools vulnerability",
  "timestamp": 1395686672.57954,
  "summary": "initramfs-tools vulnerability",
  "action": "After a standard system update you need to reboot your computer to make all\nthe necessary changes.\n",
  "isummary": "initramfs-tools used incorrect mount options.\n",
  "id": "USN-2153-1",
  "cves": [
    "https://launchpad.net/bugs/1152744"
  ]
}

=== canonical/ubuntu-security-notices/usn/6016-1.json
{
  "description": "It was discovered that thenify incorrectly handled certain inputs. If a\nuser or an automated system were tricked into opening a specially crafted\ninput file, a remote attacker could possibly use this issue to execute\narbitrary code.\n",
  "releases": {
    "focal": {
      "allbinaries": {
        "node-thenify": {
          "pocket": "security",
          "source": "node-thenify",
          "version": "3.3.0-1+deb10u1build0.20.04.1"
        }
      },
      "binaries": {
        "node-thenify": {
          "pocket": "security",
          "version": "3.3.0-1+deb10u1build0.20.04.1"
        }
      },
      "archs": {
        "source": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/universe/n/node-thenify/node-thenify_3.3.0-1+deb10u1build0.20.04.1.dsc": {
              "size": 1997,
              "md5": "fb202aee9f6efb5e9d9ef162d5c1b0ba"
            },
            "http://security.ubuntu.com/ubuntu/pool/universe/n/node-thenify/node-thenify_3.3.0-1+deb10u1build0.20.04.1.debian.tar.xz": {
              "size": 3740,
              "md5": "b1612eea227fbc18b9fc3151efcd3490"
            },
            "http://security.ubuntu.com/ubuntu/pool/universe/n/node-thenify/node-thenify_3.3.0.orig.tar.gz": {
              "size": 4511,
              "md5": "5abcb48082cf8002f73fe0e86e02ad4f"
            }
          }
        },
        "all": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/universe/n/node-thenify/node-thenify_3.3.0-1+deb10u1build0.20.04.1_all.deb": {
              "size": 4808,
              "md5": "b7e00629d30dd69387891d0aa4e7669f"
            }
          }
        }
      },
      "sources": {
        "node-thenify": {
          "version": "3.3.0-1+deb10u1build0.20.04.1",
          "description": "Promisify a callback-based function"
        }
      }
    },
    "bionic": {
      "allbinaries": {
        "node-thenify": {
          "pocket": "security",
          "source": "node-thenify",
          "version": "3.3.0-1+deb10u1build0.18.04.1"
        }
      },
      "binaries": {
        "node-thenify": {
          "pocket": "security",
          "version": "3.3.0-1+deb10u1build0.18.04.1"
        }
      },
      "archs": {
        "source": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/universe/n/node-thenify/node-thenify_3.3.0-1+deb10u1build0.18.04.1.dsc": {
              "size": 1997,
              "md5": "ecadecadd032dec922dd663c8ff38286"
            },
            "http://security.ubuntu.com/ubuntu/pool/universe/n/node-thenify/node-thenify_3.3.0.orig.tar.gz": {
              "size": 4511,
              "md5": "5abcb48082cf8002f73fe0e86e02ad4f"
            },
            "http://security.ubuntu.com/ubuntu/pool/universe/n/node-thenify/node-thenify_3.3.0-1+deb10u1build0.18.04.1.debian.tar.xz": {
              "size": 3740,
              "md5": "056385e9af1794cb9ec0e9222df16605"
            }
          }
        },
        "all": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/universe/n/node-thenify/node-thenify_3.3.0-1+deb10u1build0.18.04.1_all.deb": {
              "size": 4808,
              "md5": "95c2318b37192b87fc0d78adee0f6066"
            }
          }
        }
      },
      "sources": {
        "node-thenify": {
          "version": "3.3.0-1+deb10u1build0.18.04.1",
          "description": "Promisify a callback-based function"
        }
      }
    }
  },
  "title": "thenify vulnerability",
  "timestamp": 1681406604.8565726,
  "summary": "node-thenify vulnerability",
  "action": "In general, a standard system update will make all the necessary changes.\n",
  "cves": [
    "CVE-2020-7677"
  ],
  "id": "USN-6016-1",
  "isummary": "A security issue weas fixed in thenify.\n"
}

=== canonical/ubuntu-security-notices/usn/USN-3402-1.json
{
  "description": "It was discovered that PySAML2 incorrectly handled certain\nSAML XML requests and responses. A remote attacker could use\nthis issue to read arbitrary files.\n",
  "releases": {
    "zesty": {
      "sources": {
        "python-pysaml2": {
          "version": "3.0.0-3ubuntu1.17.04.1",
          "description": "Pure python implementation of SAML2"
        }
      },
      "binaries": {
        "python-pysaml2": {
          "version": "3.0.0-3ubuntu1.17.04.1"
        },
        "python3-pysaml2": {
          "version": "3.0.0-3ubuntu1.17.04.1"
        }
      },
      "archs": {
        "source": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/p/python-pysaml2/python-pysaml2_3.0.0-3ubuntu1.17.04.1.dsc": {
              "md5": "1adcdfee5cf4a20daca53a3cefd566e6",
              "size": 2807
            },
            "http://security.ubuntu.com/ubuntu/pool/main/p/python-pysaml2/python-pysaml2_3.0.0.orig.tar.xz": {
              "md5": "99d7caa1a52ace54f33eb66d7b337df7",
              "size": 2697844
            },
            "http://security.ubuntu.com/ubuntu/pool/main/p/python-pysaml2/python-pysaml2_3.0.0-3ubuntu1.17.04.1.debian.tar.xz": {
              "md5": "53ab7b76ce318d8856a30835da127b31",
              "size": 8832
            }
          }
        },
        "all": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/p/python-pysaml2/python-pysaml2-doc_3.0.0-3ubuntu1.17.04.1_all.deb": {
              "md5": "0cf3fa0628c4d91d6efdab97e109d728",
              "size": 45654
            },
            "http://security.ubuntu.com/ubuntu/pool/main/p/python-pysaml2/python-pysaml2_3.0.0-3ubuntu1.17.04.1_all.deb": {
              "md5": "e6d7bf6269b309016ce292f8a93340be",
              "size": 195300
            },
            "http://security.ubuntu.com/ubuntu/pool/universe/p/python-pysaml2/python3-pysaml2_3.0.0-3ubuntu1.17.04.1_all.deb": {
              "md5": "6582488cbd8b1fb2fd4ff6775619dad2",
              "size": 195384
            }
          }
        }
      }
    },
    "xenial": {
      "allbinaries": {
        "python-pysaml2-doc": {
          "pocket": "security",
          "version": "3.0.0-3ubuntu1.16.04.1"
        },
        "python-pysaml2": {
          "pocket": "security",
          "version": "3.0.0-3ubuntu1.16.04.1"
        },
        "python3-pysaml2": {
          "pocket": "security",
          "version": "3.0.0-3ubuntu1.16.04.1"
        }
      },
      "binaries": {
        "python-pysaml2": {
          "pocket": "security",
          "version": "3.0.0-3ubuntu1.16.04.1"
        },
        "python3-pysaml2": {
          "pocket": "security",
          "version": "3.0.0-3ubuntu1.16.04.1"
        }
      },
      "archs": {
        "source": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/p/python-pysaml2/python-pysaml2_3.0.0-3ubuntu1.16.04.1.debian.tar.xz": {
              "md5": "d729fb7974cdc77dd85565e5cec9b431",
              "size": 8836
            },
            "http://security.ubuntu.com/ubuntu/pool/main/p/python-pysaml2/python-pysaml2_3.0.0.orig.tar.xz": {
              "md5": "99d7caa1a52ace54f33eb66d7b337df7",
              "size": 2697844
            },
            "http://security.ubuntu.com/ubuntu/pool/main/p/python-pysaml2/python-pysaml2_3.0.0-3ubuntu1.16.04.1.dsc": {
              "md5": "3f56515deb46aae03b52ff83519cb182",
              "size": 2807
            }
          }
        },
        "all": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/p/python-pysaml2/python-pysaml2_3.0.0-3ubuntu1.16.04.1_all.deb": {
              "md5": "95e87d4eaf1044e17beb8d50529ecd15",
              "size": 195692
            },
            "http://security.ubuntu.com/ubuntu/pool/main/p/python-pysaml2/python-pysaml2-doc_3.0.0-3ubuntu1.16.04.1_all.deb": {
              "md5": "27650c8ba8397c8ad4781cf4d0dff7ca",
              "size": 46658
            },
            "http://security.ubuntu.com/ubuntu/pool/universe/p/python-pysaml2/python3-pysaml2_3.0.0-3ubuntu1.16.04.1_all.deb": {
              "md5": "7250c01660a9c897719246001c991f43",
              "size": 195912
            }
          }
        }
      },
      "sources": {
        "python-pysaml2": {
          "version": "3.0.0-3ubuntu1.16.04.1",
          "description": "Pure python implementation of SAML2"
        }
      }
    }
  },
  "title": "PySAML2 vulnerability",
  "timestamp": 1503576131.945077,
  "summary": "python-pysaml2 vulnerability",
  "action": "In general, a standard system update will make all the necessary changes.\n",
  "isummary": "The system could be made to expose sensitive information.\n",
  "id": "USN-3402-1",
  "cves": [
    "CVE-2016-10149"
  ]
}
