=== canonical/ubuntu-security-notices/schema/USN-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/canonical/ubuntu-security-notices/main/schema/USN-schema.json",
  "title": "Ubuntu Security Notice",
  "description": "A schema for describing a a security update in Ubuntu.",
  "type": "object",
  "properties": {
    "id": {
      "description": "The Security Notice id, e.g USN-0001-1",
      "type": "string"
    },
    "action": {
      "description": "Instructions on how to upgrade",
      "type": "string"
    },
    "cves": {
      "description": "A list of CVEs related to this Notice",
      "type": "array",
      "items": {
        "description": "CVE ID in the form of CVE-YYYY-NNNN",
        "type": "string"
      }
    },
    "description": {
      "description": "The description of the issue as written by the Security Team",
      "type": "string"
    },
    "is_hidden": {
      "description": "Temporary field used for testing purposes",
      "type": "string"
    },
    "isummary": {
      "description": "Short description of the vulnerability",
      "type": "string"
    },
    "releases": {
      "description": "An entry for each release name",
      "type": "object"
    },
    "summary": {
      "description": "Source package name and type of update, e.g. python-django vulnerability",
      "type": "string"
    },
    "timestamp": {
      "description": "Date in epoch format",
      "type": "number"
    },
    "title": {
      "description": "Similar to summary, but using the Official project name instead of source package name",
      "type": "string"
    }
  },
  "required": [
    "description",
    "id",
    "releases",
    "summary",
    "timestamp",
    "title"
  ],
  "additionalProperties": false
}

=== canonical/ubuntu-security-notices/usn/4608-1.json
{
  "description": "The ca-certificates package contained outdated CA certificates. This update\nrefreshes the included certificates to those contained in the 2.44 version\nof the Mozilla certificate authority bundle.\n",
  "releases": {
    "groovy": {
      "allbinaries": {
        "ca-certificates-udeb": {
          "pocket": "security",
          "version": "20201027ubuntu0.20.10.1"
        },
        "ca-certificates": {
          "pocket": "security",
          "version": "20201027ubuntu0.20.10.1"
        }
      },
      "binaries": {
        "ca-certificates": {
          "pocket": "security",
          "version": "20201027ubuntu0.20.10.1"
        }
      },
      "archs": {
        "source": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/c/ca-certificates/ca-certificates_20201027ubuntu0.20.10.1.dsc": {
              "md5": "ecc00faa5d679c4f2673c010160da6c9",
              "size": 1944
            },
            "http://security.ubuntu.com/ubuntu/pool/main/c/ca-certificates/ca-certificates_20201027ubuntu0.20.10.1.tar.xz": {
              "md5": "cb6ff9182210302fa6c34949ce5a28e4",
              "size": 242528
            }
          }
        },
        "all": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/universe/c/ca-certificates/ca-certificates-udeb_20201027ubuntu0.20.10.1_all.udeb": {
              "md5": "5148f9162ab51aa3f42df862285644a1",
              "size": 116036
            },
            "http://security.ubuntu.com/ubuntu/pool/main/c/ca-certificates/ca-certificates_20201027ubuntu0.20.10.1_all.deb": {
              "md5": "b4cbcae1a972c1f9c7994d614cf8d40a",
              "size": 145656
            }
          }
        }
      },
      "sources": {
        "ca-certificates": {
          "version": "20201027ubuntu0.20.10.1",
          "description": "Common CA certificates"
        }
      }
    },
    "bionic": {
      "allbinaries": {
        "ca-certificates-udeb": {
          "pocket": "security",
          "version": "20201027ubuntu0.18.04.1"
        },
        "ca-certificates": {
          "pocket": "security",
          "version": "20201027ubuntu0.18.04.1"
        }
      },
      "binaries": {
        "ca-certificates": {
          "pocket": "security",
          "version": "20201027ubuntu0.18.04.1"
        }
      },
      "archs": {
        "source": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/c/ca-certificates/ca-certificates_20201027ubuntu0.18.04.1.dsc": {
              "md5": "a6c33b499a628a7a4a954b4e8efc2dc1",
              "size": 1937
            },
            "http://security.ubuntu.com/ubuntu/pool/main/c/ca-certificates/ca-certificates_20201027ubuntu0.18.04.1.tar.xz": {
              "md5": "1384c9054ceb2ff974c0861a7c2fddb4",
              "size": 241956
            }
          }
        },
        "all": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/universe/c/ca-certificates/ca-certificates-udeb_20201027ubuntu0.18.04.1_all.udeb": {
              "md5": "ad326683710339c7f69de67ec02e44ae",
              "size": 123540
            },
            "http://security.ubuntu.com/ubuntu/pool/main/c/ca-certificates/ca-certificates_20201027ubuntu0.18.04.1_all.deb": {
              "md5": "8295a308f558af0ec1e76b2624c6e173",
              "size": 153104
            }
          }
        }
      },
      "sources": {
        "ca-certificates": {
          "version": "20201027ubuntu0.18.04.1",
          "description": "Common CA certificates"
        }
      }
    },
    "focal": {
      "allbinaries": {
        "ca-certificates-udeb": {
          "pocket": "security",
          "version": "20201027ubuntu0.20.04.1"
        },
        "ca-certificates": {
          "pocket": "security",
          "version": "20201027ubuntu0.20.04.1"
        }
      },
      "binaries": {
        "ca-certificates": {
          "pocket": "security",
          "version": "20201027ubuntu0.20.04.1"
        }
      },
      "archs": {
        "source": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/c/ca-certificates/ca-certificates_20201027ubuntu0.20.04.1.dsc": {
              "md5": "1eb8159a8b51355006318e37f049986e",
              "size": 1945
            },
            "http://security.ubuntu.com/ubuntu/pool/main/c/ca-certificates/ca-certificates_20201027ubuntu0.20.04.1.tar.xz": {
              "md5": "76d9a37062a1c6d5d0edce1f25f1a167",
              "size": 242452
            }
          }
        },
        "all": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/c/ca-certificates/ca-certificates_20201027ubuntu0.20.04.1_all.deb": {
              "md5": "973682d2a265ab29f22cfea1ebae18b1",
              "size": 152620
            },
            "http://security.ubuntu.com/ubuntu/pool/main/c/ca-certificates/ca-certificates-udeb_20201027ubuntu0.20.04.1_all.udeb": {
              "md5": "94d93281a51122a8e2f25b2b93302ab0",
              "size": 123540
            }
          }
        }
      },
      "sources": {
        "ca-certificates": {
          "version": "20201027ubuntu0.20.04.1",
          "description": "Common CA certificates"
        }
      }
    },
    "xenial": {
      "allbinaries": {
        "ca-certificates-udeb": {
          "pocket": "security",
          "version": "20201027ubuntu0.16.04.1"
        },
        "ca-certificates": {
          "pocket": "security",
          "version": "20201027ubuntu0.16.04.1"
        }
      },
      "binaries": {
        "ca-certificates": {
          "pocket": "security",
          "version": "20201027ubuntu0.16.04.1"
        }
      },
      "archs": {
        "source": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/c/ca-certificates/ca-certificates_20201027ubuntu0.16.04.1.dsc": {
              "md5": "cee23e0517dca64080580aa836c08a30",
              "size": 1997
            },
            "http://security.ubuntu.com/ubuntu/pool/main/c/ca-certificates/ca-certificates_20201027ubuntu0.16.04.1.tar.xz": {
              "md5": "83062eeb74197982ccf13bdb615d731c",
              "size": 241984
            }
          }
        },
        "all": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/c/ca-certificates/ca-certificates-udeb_20201027ubuntu0.16.04.1_all.udeb": {
              "md5": "047c9f8fbf4ff2d3fa75b26fb2c097dd",
              "size": 125106
            },
            "http://security.ubuntu.com/ubuntu/pool/main/c/ca-certificates/ca-certificates_20201027ubuntu0.16.04.1_all.deb": {
              "md5": "5732138fac6fd874a6a06edae5f9516e",
              "size": 155088
            }
          }
        }
      },
      "sources": {
        "ca-certificates": {
          "version": "20201027ubuntu0.16.04.1",
          "description": "Common CA certificates"
        }
      }
    }
  },
  "title": "ca-certificates update",
  "timestamp": 1603884952.4136622,
  "summary": "ca-certificates update",
  "action": "In general, a standard system update will make all the necessary changes.\n",
  "isummary": "The CA certificates in the ca-certificates package were updated.\n",
  "id": "USN-4608-1",
  "cves": [
    "https://launchpad.net/bugs/1900727"
  ]
}

=== canonical/ubuntu-security-notices/usn/USN-3690-2.json
{
  "description": "USN-3690-1 provided updated microcode for AMD processors to address\nCVE-2017-5715 (aka Spectre). Unfortunately, the update caused some\nsystems to fail to boot. This update reverts the update for Ubuntu\n14.04 LTS.\n\nWe apologize for the inconvenience.\n\nOriginal advisory details:\n\n Jann Horn discovered that microprocessors utilizing speculative execution\n and branch prediction may allow unauthorized memory reads via sidechannel\n attacks. This flaw is known as Spectre. A local attacker could use this to\n expose sensitive information, including kernel memory.\n\n This update provides the microcode updates for AMD 17H family\n processors required for the corresponding Linux kernel updates.\n",
  "releases": {
    "trusty": {
      "allbinaries": {
        "amd64-microcode": {
          "pocket": "security",
          "version": "3.20180524.1~ubuntu0.14.04.2+really20130710.1"
        }
      },
      "binaries": {
        "amd64-microcode": {
          "pocket": "security",
          "version": "3.20180524.1~ubuntu0.14.04.2+really20130710.1"
        }
      },
      "archs": {
        "source": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/a/amd64-microcode/amd64-microcode_3.20180524.1~ubuntu0.14.04.2+really20130710.1.dsc": {
              "size": 1886,
              "md5": "4a0e4050c517f049feabd919326b6f80"
            },
            "http://security.ubuntu.com/ubuntu/pool/main/a/amd64-microcode/amd64-microcode_3.20180524.1~ubuntu0.14.04.2+really20130710.1.tar.gz": {
              "size": 29547,
              "md5": "0fe802413509153b6733bff0d6a5a49f"
            }
          }
        },
        "i386": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/a/amd64-microcode/amd64-microcode_3.20180524.1~ubuntu0.14.04.2+really20130710.1_i386.deb": {
              "size": 26310,
              "md5": "47299a5cd4911922e263c239e7037036"
            }
          }
        },
        "amd64": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/a/amd64-microcode/amd64-microcode_3.20180524.1~ubuntu0.14.04.2+really20130710.1_amd64.deb": {
              "size": 26298,
              "md5": "128ccfcab6bacbb46c86ad928b627720"
            }
          }
        }
      },
      "sources": {
        "amd64-microcode": {
          "version": "3.20180524.1~ubuntu0.14.04.2+really20130710.1",
          "description": "Processor microcode firmware for AMD CPUs"
        }
      }
    }
  },
  "title": "AMD Microcode regression",
  "timestamp": 1530828801.298622,
  "summary": "amd64-microcode regression",
  "action": "After a standard system update you need to reboot your computer to make\nall the necessary changes.\n",
  "cves": [
    "https://launchpad.net/bugs/1779092"
  ],
  "id": "USN-3690-2",
  "isummary": "The system could be made to expose sensitive information.\n"
}

=== canonical/ubuntu-security-notices/usn/USN-5308-1.json
{
  "description": "It was discovered that libssh2 mishandled certain input. If libssh2 were\nused to connect to a malicious or compromised SSH server, a remote,\nunauthenticated attacker could possibly execute arbitrary code on the client \nsystem. (CVE-2019-3855)\n\nIt was discovered that libssh2 incorrectly handled prompt requests. A\nremote attacker could possibly use this issue to execute arbitrary code.\n(CVE-2019-3856)\n\nIt was discovered that libssh2 incorrectly handled SSH_MSG_CHANNEL_REQUEST\npackets. A remote attacker could possibly use this issue to execute\narbitrary code, cause a denial of service, or obtain sensitive information. \n(CVE-2019-3857, CVE-2019-3862)\n\nIt was discovered that libssh2 incorrectly handled specially crafted SFTP\npackets. A remote attacker could possibly use this issue to cause a denial\nof service or obtain sensitive information. (CVE-2019-3858)\n\nIt was discovered that libssh2 incorrectly handled certain specially\ncrafted packets. A remote attacker could possibly use this issue to cause a\ndenial of service or obtain sensitive information. (CVE-2019-3859)\n\nIt was discovered that libssh2 incorrectly handled SFTP packets with empty\npayloads. A remote attacker could possibly use this issue to cause a denial\nof service or obtain sensitive information. (CVE-2019-3860)\n\nIt was discovered that libssh2 incorrectly handled padding values in SSH\npackets. A remote attacker could possibly use this issue to cause a denial\nof service or obtain sensitive information. (CVE-2019-3861)\n\nIt was discovered that libssh2 incorrectly handled interactive response\nmessages length. A remote attacker could possibly use this issue to execute\narbitrary code. (CVE-2019-3863)\n\nIt was discovered that libssh2 incorrectly handled the Diffie Hellman key\nexchange. A remote attacker could possibly use this issue to cause a denial\nof service or obtain sensitive information. (CVE-2019-13115)\n\nIt was discovered that libssh2 incorrectly handled bound checks in\nSSH_MSG_DISCONNECT. A remote attacker could possibly use this issue to\ncause a denial of service or obtain sensitive information. (CVE-2019-17498)\n",
  "releases": {
    "xenial": {
      "sources": {
        "libssh2": {
          "version": "1.5.0-2ubuntu0.1+esm1",
          "description": "Client-side C library implementing the SSH2 protocol"
        }
      },
      "binaries": {
        "libssh2-1": {
          "pocket": "esm-apps",
          "version": "1.5.0-2ubuntu0.1+esm1"
        }
      },
      "allbinaries": {
        "libssh2-1-dev": {
          "pocket": "esm-apps",
          "source": "libssh2",
          "version": "1.5.0-2ubuntu0.1+esm1"
        },
        "libssh2-1": {
          "pocket": "esm-apps",
          "source": "libssh2",
          "version": "1.5.0-2ubuntu0.1+esm1"
        }
      }
    }
  },
  "title": "libssh2 vulnerabilities",
  "timestamp": 1646696821.4715524,
  "summary": "libssh2 vulnerabilities",
  "action": "In general, a standard system update will make all the necessary changes.\n",
  "is_hidden": "false",
  "cves": [
    "CVE-2019-13115",
    "CVE-2019-17498",
    "CVE-2019-3855",
    "CVE-2019-3856",
    "CVE-2019-3857",
    "CVE-2019-3858",
    "CVE-2019-3859",
    "CVE-2019-3860",
    "CVE-2019-3861",
    "CVE-2019-3862",
    "CVE-2019-3863"
  ],
  "id": "USN-5308-1",
  "isummary": "Several security issues were fixed in libssh2.\n"
}

=== canonical/ubuntu-security-notices/usn/2935-3.json
{
  "description": "USN-2935-1 fixed vulnerabilities in PAM. The updates contained a packaging\nchange that prevented upgrades in certain multiarch environments. USN-2935-2\nintended to fix the problem but was incomplete for Ubuntu 12.04 LTS. This\nupdate fixes the problem in Ubuntu 12.04 LTS.\n\nWe apologize for the inconvenience.\n\nOriginal advisory details:\n\n It was discovered that the PAM pam_userdb module incorrectly used a\n case-insensitive method when comparing hashed passwords. A local attacker\n could possibly use this issue to make brute force attacks easier. This\n issue only affected Ubuntu 12.04 LTS and Ubuntu 14.04 LTS. (CVE-2013-7041)\n \n Sebastian Krahmer discovered that the PAM pam_timestamp module incorrectly\n performed filtering. A local attacker could use this issue to create\n arbitrary files, or possibly bypass authentication. This issue only\n affected Ubuntu 12.04 LTS and Ubuntu 14.04 LTS. (CVE-2014-2583)\n \n Sebastien Macke discovered that the PAM pam_unix module incorrectly handled\n large passwords. A local attacker could possibly use this issue in certain\n environments to enumerate usernames or cause a denial of service.\n (CVE-2015-3238)\n",
  "releases": {
    "precise": {
      "sources": {
        "pam": {
          "version": "1.1.3-7ubuntu2.3",
          "description": "Pluggable Authentication Modules"
        }
      },
      "binaries": {
        "libpam-modules": {
          "version": "1.1.3-7ubuntu2.3"
        }
      },
      "archs": {
        "all": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/p/pam/libpam-runtime_1.1.3-7ubuntu2.3_all.deb": {
              "size": 40598,
              "md5": "d9dc8bbf0022993f70bec2dac8b88ddf"
            },
            "http://security.ubuntu.com/ubuntu/pool/main/p/pam/libpam-doc_1.1.3-7ubuntu2.3_all.deb": {
              "size": 257652,
              "md5": "244541771e3566886c6e7c7c3a8cc0c7"
            }
          }
        },
        "amd64": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/p/pam/libpam0g_1.1.3-7ubuntu2.3_amd64.deb": {
              "size": 61762,
              "md5": "0d89ba1c8d3af8b0a85f8c4fa2e25e73"
            },
            "http://security.ubuntu.com/ubuntu/pool/main/p/pam/libpam0g-dev_1.1.3-7ubuntu2.3_amd64.deb": {
              "size": 120522,
              "md5": "0216ce223ced4bba53241d0cf13fb517"
            },
            "http://security.ubuntu.com/ubuntu/pool/main/p/pam/libpam-modules_1.1.3-7ubuntu2.3_amd64.deb": {
              "size": 275812,
              "md5": "491f559cf76480881a8d35f4eae26bd4"
            },
            "http://security.ubuntu.com/ubuntu/pool/main/p/pam/libpam-cracklib_1.1.3-7ubuntu2.3_amd64.deb": {
              "size": 13040,
              "md5": "fe670e5cf73165fd1fa2994578ff7847"
            },
            "http://security.ubuntu.com/ubuntu/pool/main/p/pam/libpam-modules-bin_1.1.3-7ubuntu2.3_amd64.deb": {
              "size": 42442,
              "md5": "6b080e268367c031e4838fa51934563f"
            }
          }
        },
        "powerpc": {
          "urls": {
            "http://ports.ubuntu.com/pool/main/p/pam/libpam-modules_1.1.3-7ubuntu2.3_powerpc.deb": {
              "size": 274508,
              "md5": "39b2a90d9b316c2143b8e7a2cabb2d2c"
            },
            "http://ports.ubuntu.com/pool/main/p/pam/libpam0g-dev_1.1.3-7ubuntu2.3_powerpc.deb": {
              "size": 118934,
              "md5": "1c8a6f7b15363b736068c7494be69802"
            },
            "http://ports.ubuntu.com/pool/main/p/pam/libpam-cracklib_1.1.3-7ubuntu2.3_powerpc.deb": {
              "size": 13138,
              "md5": "335fd9691622c2210d8beab387fb0300"
            },
            "http://ports.ubuntu.com/pool/main/p/pam/libpam-modules-bin_1.1.3-7ubuntu2.3_powerpc.deb": {
              "size": 31500,
              "md5": "d62d337fca4a1feb9b6345bb4c896d10"
            },
            "http://ports.ubuntu.com/pool/main/p/pam/libpam0g_1.1.3-7ubuntu2.3_powerpc.deb": {
              "size": 60824,
              "md5": "3630df24a828aa8a9da3c5729e715912"
            }
          }
        },
        "source": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/p/pam/pam_1.1.3-7ubuntu2.3.dsc": {
              "size": 2511,
              "md5": "1f77c3b304f739375912af38cb145e0e"
            },
            "http://security.ubuntu.com/ubuntu/pool/main/p/pam/pam_1.1.3.orig.tar.gz": {
              "size": 1768872,
              "md5": "9a977619848cfed372d9b361e328ec99"
            },
            "http://security.ubuntu.com/ubuntu/pool/main/p/pam/pam_1.1.3-7ubuntu2.3.diff.gz": {
              "size": 293924,
              "md5": "0fb463f5f9b3401104ab9db52a175d0b"
            }
          }
        },
        "i386": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/p/pam/libpam0g_1.1.3-7ubuntu2.3_i386.deb": {
              "size": 61098,
              "md5": "20500299578b590862305d4d15586f7a"
            },
            "http://security.ubuntu.com/ubuntu/pool/main/p/pam/libpam-modules-bin_1.1.3-7ubuntu2.3_i386.deb": {
              "size": 42588,
              "md5": "a9d107d0f902a6d25a3019e264a37736"
            },
            "http://security.ubuntu.com/ubuntu/pool/main/p/pam/libpam-cracklib_1.1.3-7ubuntu2.3_i386.deb": {
              "size": 13058,
              "md5": "ad05ca75e5b56a9f2c40f288d9692f76"
            },
            "http://security.ubuntu.com/ubuntu/pool/main/p/pam/libpam0g-dev_1.1.3-7ubuntu2.3_i386.deb": {
              "size": 117926,
              "md5": "be1eb38f01f77fb5356200cac1e7e19c"
            },
            "http://security.ubuntu.com/ubuntu/pool/main/p/pam/libpam-modules_1.1.3-7ubuntu2.3_i386.deb": {
              "size": 271090,
              "md5": "afbc0ab927cf8096b6bbef3501c6a511"
            }
          }
        },
        "armel": {
          "urls": {
            "http://ports.ubuntu.com/pool/main/p/pam/libpam0g-dev_1.1.3-7ubuntu2.3_armel.deb": {
              "size": 110744,
              "md5": "be225025f0ff063467b0d52aef28622f"
            },
            "http://ports.ubuntu.com/pool/main/p/pam/libpam-modules-bin_1.1.3-7ubuntu2.3_armel.deb": {
              "size": 35864,
              "md5": "c7bb950a0b85aed528800577d30bbddf"
            },
            "http://ports.ubuntu.com/pool/main/p/pam/libpam0g_1.1.3-7ubuntu2.3_armel.deb": {
              "size": 54004,
              "md5": "889cd5ed4653a2d438a953ea7afa08e6"
            },
            "http://ports.ubuntu.com/pool/main/p/pam/libpam-cracklib_1.1.3-7ubuntu2.3_armel.deb": {
              "size": 12064,
              "md5": "5c7e4573292a35d39b913b23313fca6c"
            },
            "http://ports.ubuntu.com/pool/main/p/pam/libpam-modules_1.1.3-7ubuntu2.3_armel.deb": {
              "size": 243350,
              "md5": "f9efdbae2b6c3b6a665d7ba30682e2e1"
            }
          }
        },
        "armhf": {
          "urls": {
            "http://ports.ubuntu.com/pool/main/p/pam/libpam-modules_1.1.3-7ubuntu2.3_armhf.deb": {
              "size": 242328,
              "md5": "de20625babe6fcadfab2855e304913c0"
            },
            "http://ports.ubuntu.com/pool/main/p/pam/libpam-cracklib_1.1.3-7ubuntu2.3_armhf.deb": {
              "size": 12054,
              "md5": "27e6a4ba85a0e94e2f6318f917395d3f"
            },
            "http://ports.ubuntu.com/pool/main/p/pam/libpam-modules-bin_1.1.3-7ubuntu2.3_armhf.deb": {
              "size": 36274,
              "md5": "b5989abc2c5aa12c0872b11ae89bd41d"
            },
            "http://ports.ubuntu.com/pool/main/p/pam/libpam0g-dev_1.1.3-7ubuntu2.3_armhf.deb": {
              "size": 110878,
              "md5": "6d82e3919c962c641d450d6cbf93bf2d"
            },
            "http://ports.ubuntu.com/pool/main/p/pam/libpam0g_1.1.3-7ubuntu2.3_armhf.deb": {
              "size": 54632,
              "md5": "0351cb22a3dbca9a74a66f4f691273e1"
            }
          }
        }
      }
    }
  },
  "title": "PAM regression",
  "timestamp": 1458247061.803407,
  "summary": "pam regression",
  "action": "In general, a standard system update will make all the necessary changes.\n",
  "cves": [
    "https://launchpad.net/bugs/1558597",
    "http://www.ubuntu.com/usn/usn-2935-2"
  ],
  "id": "USN-2935-3",
  "isummary": "USN-2935-1 introduced a regression in PAM.\n"
}
